// Generated by npm run build:relay. Edit server/worker.js and server/cloudflare.js.
// Only fixed aircraft-provider paths are allowed; this is never an arbitrary proxy.
export function upstreamForPath(path, telemetryProvider = 'adsb.fi') {
  const nearby = path.match(/^\/api\/nearby\/(-?\d+(?:\.\d+)?)\/(-?\d+(?:\.\d+)?)\/(50|100|250)$/);
  const route = path.match(/^\/api\/route\/([A-Z]{3}\d[A-Z0-9]{0,6})\/(-?\d+(?:\.\d+)?)\/(-?\d+(?:\.\d+)?)$/);
  const callsign = path.match(/^\/api\/callsign\/([A-Z]{3}\d[A-Z0-9]{0,6})$/);
  const airline = path.match(/^\/api\/airline\/([A-Z]{3})$/);
  if (callsign) return 'https://api.adsbdb.com/v0/callsign/' + callsign[1];
  if (airline) return 'https://api.adsbdb.com/v0/airline/' + airline[1];
  if ((!nearby && !route) || (route && telemetryProvider !== 'adsb.lol')) return null;
  const lat = Number(nearby ? nearby[1] : route[2]);
  const lon = Number(nearby ? nearby[2] : route[3]);
  if (Math.abs(lat) > 90 || Math.abs(lon) > 180) return null;
  return nearby
    ? (telemetryProvider === 'adsb.lol' ? 'https://api.adsb.lol/v2/point/' + lat + '/' + lon + '/' + nearby[3] : 'https://opendata.adsb.fi/api/v3/lat/' + lat + '/lon/' + lon + '/dist/' + nearby[3])
    : 'https://api.adsb.lol/api/0/route/' + route[1] + '/' + lat + '/' + lon;
}
const headers = {
  'Content-Type': 'application/json; charset=utf-8',
  'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'no-referrer', 'Permissions-Policy': 'geolocation=(self)',
};
const MAX_BYTES = 5_000_000;
function json(status, body, extra = {}) {
  return new Response(typeof body === 'string' ? body : JSON.stringify(body), {
    status, headers: { ...headers, ...extra },
  });
}
export function retrySeconds(raw) {
  const n = Number(raw);
  return /^\d+$/.test(raw ?? '') && Number.isSafeInteger(n) ? Math.max(1, n) : 60;
}
export async function readJson(response) {
  if (!response.body) throw new Error('Missing response');
  const reader = response.body.getReader();
  const chunks = [];
  let size = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      size += value.byteLength;
      if (size > MAX_BYTES) throw new Error('Response too large');
      chunks.push(value);
    }
  } catch (error) {
    await reader.cancel().catch(() => {});
    throw error;
  }
  const bytes = new Uint8Array(size);
  let offset = 0;
  for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }
  const text = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  JSON.parse(text);
  return { text, size };
}
// Cancel queued work promptly instead of leaving a disconnected request asleep.
function waitForSlot(delay, signal) {
  return new Promise((resolve, reject) => {
    const done = () => { signal.removeEventListener('abort', cancel); resolve(); };
    const timer = setTimeout(done, delay);
    const cancel = () => { clearTimeout(timer); reject(new DOMException('Request cancelled', 'AbortError')); };
    if (signal.aborted) cancel();
    else signal.addEventListener('abort', cancel, { once: true });
  });
}

export function createHostedHandler({ assets = {}, fetcher = (url, options) => globalThis.fetch(url, options), now = Date.now, nearbyIntervalMs = 1000, allowedOrigin = null } = {}) {
  const cache = new Map();
  const recent = [];
  let bytes = 0, inFlight = 0, pauseUntil = 0, nextNearbyAt = 0;
  const drop = key => { bytes -= cache.get(key).size; cache.delete(key); };
  return {
    async fetch(request) {
      const url = new URL(request.url);
      if (url.pathname === '/config.json') url.pathname = '/api/config';
      if (!url.pathname.startsWith('/api/')) {
        if (!['GET', 'HEAD'].includes(request.method)) return json(405, { error: 'Read-only site' });
        const assetPath = url.pathname === '/' ? '/index.html' : url.pathname;
        const asset = Object.hasOwn(assets, assetPath) ? assets[assetPath] : null;
        if (!asset) return new Response('Not found', { status: 404 });
        return new Response(request.method === 'HEAD' ? null : asset.body, {
          headers: { ...headers, 'Content-Type': asset.type, 'Cache-Control': 'no-cache' },
        });
      }
      if (request.method !== 'GET') return json(405, { error: 'Data requests require GET' });
      const origin = request.headers.get('origin');
      const fetchSite = request.headers.get('sec-fetch-site');
      if ((origin && origin !== url.origin && origin !== allowedOrigin)
        || (fetchSite && !['same-origin', 'none'].includes(fetchSite) && !(origin && origin === allowedOrigin))) {
        return json(403, { error: 'Same-origin requests only' });
      }
      if (url.search) return json(400, { error: 'Unsupported data request' });
      if (url.pathname === '/api/config') return json(200, { relay: true, telemetryProvider: 'adsb.fi', routeProvider: 'adsbdb' });
      const upstream = upstreamForPath(url.pathname);
      if (!upstream) return json(400, { error: 'Unsupported data request' });
      const timestamp = now();
      if (pauseUntil > timestamp) return json(429, { error: 'Provider requests are paused' }, { 'Retry-After': String(Math.ceil((pauseUntil - timestamp) / 1000)) });
      for (const [key, entry] of cache) if (timestamp - entry.at >= 20000) drop(key);
      if (cache.has(upstream)) return json(200, cache.get(upstream).text);
      while (recent.length && recent[0] <= timestamp - 60000) recent.shift();
      if (recent.length >= 40 || inFlight >= 3) return json(429, { error: 'Please wait before searching again' }, { 'Retry-After': '30' });
      recent.push(timestamp);
      inFlight++;
      // Incoming Request.signal is optional in the hosted Worker runtime.
      const timeout = new AbortController();
      const timer = setTimeout(() => timeout.abort(), 10000);
      const incoming = request.signal;
      const cancel = () => timeout.abort();
      if (incoming?.aborted) cancel();
      else incoming?.addEventListener?.('abort', cancel, { once: true });
      try {
        // adsb.fi allows one request per second. Reserve slots before waiting.
        if (upstream.startsWith('https://opendata.adsb.fi/')) {
          const startAt = Math.max(now(), nextNearbyAt);
          nextNearbyAt = startAt + nearbyIntervalMs;
          const delay = Math.max(0, startAt - now());
          if (delay) await waitForSlot(delay, timeout.signal);
        }
        if (timeout.signal.aborted) throw new DOMException('Request cancelled', 'AbortError');
        // Another concurrent request may have received a provider pause while
        // this request waited for its slot. Do not send more work during it.
        if (pauseUntil > now()) return json(429, { error: 'Provider requests are paused' }, {
          'Retry-After': String(Math.ceil((pauseUntil - now()) / 1000)),
        });
        const response = await fetcher(upstream, {
          signal: timeout.signal,
          redirect: 'manual',
          headers: { Accept: 'application/json', 'User-Agent': 'Flightguesser/0.1 (+https://bttlbmb.github.io/flightguesser/)' },
        });
        if (response.status === 429) {
          const seconds = retrySeconds(response.headers.get('retry-after'));
          pauseUntil = Math.max(pauseUntil, now() + seconds * 1000);
          return json(429, { error: 'Flight data service needs a pause' }, { 'Retry-After': String(seconds) });
        }
        if (!response.ok) {
          console.warn('Flight provider response', new URL(upstream).hostname, response.status);
          return json(502, { error: 'Live flight data is unavailable' });
        }
        const entry = await readJson(response);
        // Bound cached bytes across nearby snapshots, not just the number of entries.
        if (cache.has(upstream)) drop(upstream);
        while (cache.size && (cache.size >= 80 || bytes + entry.size > MAX_BYTES)) drop(cache.keys().next().value);
        cache.set(upstream, { ...entry, at: now() });
        bytes += entry.size;
        return json(200, entry.text);
      } catch (error) {
        console.warn('Flight relay failure', error.name, String(error.message).replace(/https?:\/\/\S+/g, '[upstream]').slice(0, 300));
        return json(502, { error: 'Live flight data is unavailable' });
      } finally {
        clearTimeout(timer);
        incoming?.removeEventListener?.('abort', cancel);
        inFlight--;
      }
    },
  };
}


const websiteOrigin = 'https://bttlbmb.github.io';

export function createCloudflareRelay(options = {}) {
  const handler = createHostedHandler({ ...options, allowedOrigin: websiteOrigin });
  return {
    async fetch(request) {
      const url = new URL(request.url);
      const origin = request.headers.get('origin');
      const cors = origin === websiteOrigin ? {
        'Access-Control-Allow-Origin': websiteOrigin,
        'Access-Control-Allow-Methods': 'GET, OPTIONS',
        'Access-Control-Expose-Headers': 'Retry-After',
        'Access-Control-Max-Age': '3600',
      } : {};
      const reply = (status, body) => new Response(body ? JSON.stringify(body) : null, {
        status, headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store', Vary: 'Origin', ...cors },
      });
      if (origin && origin !== websiteOrigin) return reply(403, { error: 'Website origin is not allowed' });
      if (url.pathname === '/' && request.method === 'GET') return reply(200, {
        service: 'Flightguesser relay', website: websiteOrigin + '/flightguesser/',
      });
      if (url.search || (url.pathname !== '/api/config' && !upstreamForPath(url.pathname))) {
        return reply(400, { error: 'Unsupported data request' });
      }
      if (request.method === 'OPTIONS') {
        if (origin !== websiteOrigin || request.headers.get('access-control-request-method') !== 'GET'
          || request.headers.get('access-control-request-headers')) return reply(403, { error: 'Unsupported preflight request' });
        return reply(204);
      }
      const response = await handler.fetch(request);
      const headers = new Headers(response.headers);
      headers.set('Vary', 'Origin');
      for (const [name, value] of Object.entries(cors)) headers.set(name, value);
      return new Response(response.body, { status: response.status, headers });
    },
  };
}

export default createCloudflareRelay();
