import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
const core = await readFile(join(root, 'server/worker.js'), 'utf8');
const entry = (await readFile(join(root, 'server/cloudflare.js'), 'utf8'))
  .replace("import { createHostedHandler, upstreamForPath } from './worker.js';\n", '');
await mkdir(join(root, 'cloudflare'), { recursive: true });
await writeFile(join(root, 'cloudflare/worker.js'),
  '// Generated by npm run build:relay. Edit server/worker.js and server/cloudflare.js.\n' + core + '\n' + entry);
console.log('Built cloudflare/worker.js — paste this complete file into the Cloudflare Worker editor.');
